package ch.romasch.gradle.yaml.config.task

import java.io.File

class YamlConfigGeneratorTaskImpl(val input: Collection<String>, val targetPackage: String, val targetDirectory: File) {

    fun packageInfoContent() = "@javax.annotation.Generated(\"Generated by YamlConfigurationGeneratorPlugin\")\n" +
            "package $targetPackage;\n"

    fun execute() {
        createPackageInfo()
        createJavaClasses()
    }

    private fun createPackageInfo()  = createFile("package-info", packageInfoContent())

    private fun createJavaClasses() {
        generateJavaCode(input, targetPackage).forEach {name, content ->
            createFile(name, content)
        }
    }
    
    private fun createFile(name: String, content: String) {
        val file = File(targetDirectory, "$name.java")
        file.createNewFile()
        file.writeText(content)
    }

}
